apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: supernova-role
  namespace: supernova
rules:
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: supernova-rolebinding
  namespace: supernova
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: supernova-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: supernova