apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
  namespace: supernova
spec:
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
  selector:
    app: scheduler

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  namespace: supernova
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
        - name: scheduler
          image: exiasun/scheduler:latest
          imagePullPolicy: Never
