apiVersion: v1
kind: Service
metadata:
  name: scheduler
  namespace: supernova
spec:
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
  selector:
    app: scheduler

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-executor
  namespace: supernova
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-executor
  template:
    metadata:
      labels:
        app: http-executor
    spec:
      containers:
        - name: http-executor
          image: exiasun/http-executor:latest
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
