// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"supernova/executor/processor"
	"supernova/executor/service"
	"supernova/pkg/discovery"
)

// Injectors from wire.go:

func genExecutor(instanceID string, tags []string, processor2 []processor.JobProcessor, serveConf *discovery.ServiceServeConf, processorCount int, client discovery.Client, extraConf map[string]string) (*Executor, error) {
	duplicateService := service.NewDuplicateService()
	statisticsService := service.NewStatisticsService()
	processorService := service.NewProcessorService()
	executeService := service.NewExecuteService(statisticsService, processorService, duplicateService, processorCount)
	executor := newExecutorInner(instanceID, tags, processor2, serveConf, processorCount, extraConf, client, duplicateService, executeService, processorService, statisticsService)
	return executor, nil
}
