apiVersion: v1
kind: Service
metadata:
  name: http-executor
  namespace: supernova
spec:
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
  selector:
    app: http-executor

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-executor
  namespace: supernova
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-executor
  template:
    metadata:
      labels:
        app: http-executor
    spec:
      containers:
      - name: http-executor
        image: exiasun/http-executor:latest
        imagePullPolicy: Never
