apiVersion: v1
kind: Service
metadata:
  name: http-executor
  namespace: supernova
  labels:
    SupernovaExecutor: "1"
    #需要同discovery/k8s.go中对应上
    ExecutorProtoc: "Grpc"
    ExecutorTag: "X-Tag-Glue-Http"
spec:
  ports:
    - protocol: TCP
      name: grpc
      port: 7070
      targetPort: 7070
  selector:
    app: http-executor

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-executor
  namespace: supernova
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http-executor
  template:
    metadata:
      labels:
        app: http-executor
    spec:
      containers:
      - name: http-executor
        image: exiasun/http-executor:latest
        imagePullPolicy: Never
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9090
          initialDelaySeconds: 5
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9090
          initialDelaySeconds: 3
          periodSeconds: 3
