// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/kitex-contrib/obs-opentelemetry/provider"
	"supernova/pkg/discovery"
	"supernova/scheduler/operator/schedule_operator"
	"supernova/scheduler/service"
)

// Injectors from wire.go:

func genScheduler(instanceID string, enableTrace bool, traceProvider provider.OtelProvider, scheduleOperator schedule_operator.Operator, client discovery.ExecutorDiscoveryClient, schedulerWorkerCount int) (*Scheduler, error) {
	statisticsService := service.NewStatisticsService(instanceID, enableTrace)
	jobService := service.NewJobService(scheduleOperator, statisticsService)
	triggerService := service.NewTriggerService(scheduleOperator, statisticsService)
	onFireService := service.NewOnFireService(scheduleOperator, statisticsService)
	executorManageService := service.NewExecutorManageService(statisticsService, client)
	executorRouteService := service.NewExecutorRouteService(executorManageService)
	scheduleService := service.NewScheduleService(statisticsService, jobService, triggerService, onFireService, executorRouteService, schedulerWorkerCount, executorManageService, enableTrace)
	scheduler := newSchedulerInner(instanceID, traceProvider, enableTrace, scheduleOperator, scheduleService, statisticsService, executorRouteService, executorManageService, jobService, triggerService, onFireService)
	return scheduler, nil
}
