t1:
	go test -v stress_test.go -timeout 1000s 

t2:
	go test -v kill_scheduler_test.go -timeout 1000s 

t3:
	go test -v executor_graceful_stop_test.go -timeout 1000s 

t4:
	go test -v k8s_test.go -timeout 1000s 
